sudo: false

language: node_js

matrix:
  include:
    - node_js: "4.4.7"
    - node_js: "5.12.0"
    - node_js: "6.3.1"

after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage"
notifications:
  email:
    - andrey.kuznetsov48@yandex.ru
